#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with
#1 and 2, the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89,..
#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.



fibonacci_list = [1, 2]
even_fibonacci=[]
x=fibonacci_list[-1]

while x<=4000000:
    if (fibonacci_list[-1]+fibonacci_list[-2])<=4000000:
        fibonacci_list.append(fibonacci_list[-1] + fibonacci_list[-2])
        x = fibonacci_list[-1]
        print(x)
        print(fibonacci_list)
    else:
        break

for b in fibonacci_list:
    print(b)
    if b%2==0:
        even_fibonacci.append(b)
    else:
        print("no")

# print (even_fibonacci)
even_added= sum(even_fibonacci)
print(even_added)
